# Generated by Django 3.1.7 on 2021-04-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_description', models.CharField(max_length=100)),
                ('event_time', models.TimeField()),
                ('event_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('is_student_or_staff', models.BooleanField()),
                ('registration_link', models.CharField(max_length=100)),
                ('postor', models.ImageField(default='', upload_to='Events/Postors')),
            ],
        ),
    ]
