# Generated by Django 3.1.7 on 2021-04-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='is_student_or_staff',
            new_name='is_student',
        ),
        migrations.AddField(
            model_name='event',
            name='event_title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
