# Generated by Django 3.1.2 on 2021-04-02 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
        ('events', '0002_auto_20210402_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='approval_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='college.staff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='conductor_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='college.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='dept_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='college.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_place',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='college.place'),
            preserve_default=False,
        ),
    ]
