# Generated by Django 3.1.2 on 2021-04-02 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
        ('events', '0004_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='approval_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='college.staff'),
        ),
    ]
