# Generated by Django 3.1.2 on 2021-04-02 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
        ('events', '0005_auto_20210403_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='conductor_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='college.student'),
        ),
        migrations.AlterField(
            model_name='event',
            name='dept_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='college.department'),
        ),
    ]
