# Generated by Django 3.1.2 on 2021-04-02 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_auto_20210403_0212'),
        ('events', '0006_auto_20210403_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_place',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='college.place'),
        ),
    ]
