# Generated by Django 3.1.2 on 2021-04-02 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_auto_20210403_0212'),
        ('events', '0007_auto_20210403_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='approval_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college.staff'),
        ),
        migrations.AlterField(
            model_name='event',
            name='conductor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college.student'),
        ),
        migrations.AlterField(
            model_name='event',
            name='dept_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college.department'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college.place'),
        ),
    ]
