# Generated by Django 3.1.2 on 2021-04-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20210403_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
