# Generated by Django 3.1.7 on 2021-04-03 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20210403_1420'),
        ('events', '0010_event_status'),
    ]

    operations = [
    ]
