# Generated by Django 3.1.7 on 2021-04-03 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0008_auto_20210403_1314'),
        ('events', '0011_merge_20210403_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='committee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college.committee'),
        ),
    ]
