# Generated by Django 3.1.7 on 2021-04-02 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_id', models.AutoField(primary_key=True, serialize=False)),
                ('place_name', models.CharField(max_length=50)),
                ('capactiy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_email', models.CharField(default='', max_length=100, unique=True)),
                ('staff_password', models.CharField(default='', max_length=200)),
                ('staff_fname', models.CharField(default='', max_length=50)),
                ('staff_lname', models.CharField(default='', max_length=50)),
                ('designation', models.CharField(default='', max_length=20)),
                ('photo', models.ImageField(upload_to='college/staff/')),
                ('phone_number', models.IntegerField()),
                ('last_active', models.TimeField(auto_now=True)),
                ('Staff_type', models.IntegerField()),
                ('gender', models.TextField(default='', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('stud_fname', models.CharField(max_length=50)),
                ('stud_lname', models.CharField(max_length=50)),
                ('is_privileged', models.BooleanField(default=False)),
                ('stud_email', models.EmailField(default='', max_length=254)),
                ('stud_password', models.CharField(max_length=2000)),
                ('stud_photo', models.ImageField(upload_to='college/student/')),
                ('gender', models.CharField(default='', max_length=1)),
                ('dept_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='department', to='college.department')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='dep_hod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.staff'),
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('committee_id', models.AutoField(primary_key=True, serialize=False)),
                ('comm_name', models.CharField(max_length=50)),
                ('comm_level', models.CharField(max_length=30)),
                ('comm_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='college.student')),
            ],
        ),
    ]
