# Generated by Django 3.1.2 on 2021-04-02 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_id', models.AutoField(primary_key=True, serialize=False)),
                ('place_name', models.CharField(max_length=50)),
                ('capactiy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_privileged', models.BooleanField(default=False)),
                ('stud_photo', models.ImageField(upload_to='college/student/')),
                ('gender', models.CharField(default='', max_length=1)),
                ('dept_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='department', to='college.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='college/staff/')),
                ('phone_number', models.IntegerField()),
                ('last_active', models.TimeField(auto_now=True)),
                ('Staff_type', models.IntegerField()),
                ('gender', models.TextField(default='', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='dep_hod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.staff'),
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('committee_id', models.AutoField(primary_key=True, serialize=False)),
                ('comm_name', models.CharField(max_length=50)),
                ('comm_level', models.CharField(max_length=30)),
                ('comm_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='college.student')),
            ],
        ),
    ]
