# Generated by Django 3.1.7 on 2021-04-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.ImageField(null=True, upload_to='college/staff/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stud_photo',
            field=models.ImageField(null=True, upload_to='college/student/'),
        ),
    ]
