# Generated by Django 3.1.2 on 2021-04-02 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('committee_id', models.AutoField(primary_key=True, serialize=False)),
                ('comm_name', models.CharField(max_length=50)),
                ('comm_level', models.CharField(max_length=30)),
                ('comm_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='college.student')),
            ],
        ),
    ]
