# Generated by Django 3.1.7 on 2021-04-02 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_committee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='type',
            new_name='Staff_type',
        ),
    ]
