# Generated by Django 3.1.2 on 2021-04-02 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_remove_department_dep_hod'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dep_hod',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='college.staff'),
            preserve_default=False,
        ),
    ]
