# Generated by Django 3.1.7 on 2021-04-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_auto_20210403_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stud_photo',
            field=models.ImageField(blank=True, null=True, upload_to='college/student/'),
        ),
    ]
