# Generated by Django 3.1.2 on 2021-04-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_auto_20210402_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.ImageField(upload_to='college/staff/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stud_photo',
            field=models.ImageField(upload_to='college/student/'),
        ),
    ]
