# Generated by Django 3.1.7 on 2021-04-03 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_auto_20210403_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='deptartment_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college.department'),
        ),
    ]
