# Generated by Django 3.1.7 on 2021-04-03 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0007_auto_20210403_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='deptartment_id',
            new_name='dept_id',
        ),
    ]
