# Generated by Django 3.1.7 on 2021-04-03 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0009_studentincommitteed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentInCommitteed',
            new_name='StudentInCommittees',
        ),
    ]
